Update patch set 2
Patch Set 2:

This causes the build to fail for stable-2.12 an stable-2.13:

  10:44:19 /home/jenkins/workspace/plugin-events-log-stable-2.13/plugins/events-log/src/main/java/com/ericsson/gerrit/plugins/eventslog/sql/SQLQueryMaker.java:34: error: package java.util.function does not exist
  10:44:19 import java.util.function.Supplier;

Full logs:
https://gerrit-ci.gerritforge.com/view/Plugins-stable-2.12/job/plugin-events-log-stable-2.12/10/console
https://gerrit-ci.gerritforge.com/view/Plugins-stable-2.13/job/plugin-events-log-stable-2.13/5/console

I think it's because Supplier was introduced with Java 8, but we build stable-2.13 with Java 7

https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html

Patch-set: 2
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>