Update patch set 3
Patch Set 3: Verified+1

(tests fail with


1) noRetryOnZeroMaxTries(com.ericsson.gerrit.plugins.eventslog.sql.SQLStoreTest)
org.h2.jdbc.JdbcSQLException: Table "ChangeEvents" not found; SQL statement:
DROP TABLE ChangeEvents [42102-176]

though not caused by this change i doint think.

Patch-set: 3
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1