Update patch set 3
Patch Set 3:

Tests fail with

paladox@gerrit-test:~/gerrit$ bazel test plugins/events-log:events_log_tests
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 test target...
ERROR: /home/paladox/gerrit/plugins/events-log/BUILD:25:1: Java compilation in rule '//plugins/events-log:events_log_tests' failed: Worker process sent response with exit code: 1.
plugins/events-log/src/test/java/com/ericsson/gerrit/plugins/eventslog/sql/SQLEntryTest.java:74: error: [SelfEquals] An object is tested for equality to itself
    assertThat(entry1.equals(entry1)).isTrue();
                            ^
    (see http://errorprone.info/bugpattern/SelfEquals)
Target //plugins/events-log:events_log_tests failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 159.578s, Critical Path: 135.61s

Executed 0 out of 1 test: 1 fails to build.

which is not caused by this patch :)

Patch-set: 3
Reviewer: Gerrit User 1029953 <1029953@173816e5-2b9a-37c3-8a2e-48639d4f1153>